apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  label:
   jojo-version: 3
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: ghcr.io/tac-ichiro/ks-guestbook-demo:0.8
        name: guestbook-ui
        ports:
        - containerPort: 8080
